language: android

sudo: true

android:
  components:
  - build-tools-28.0.3

jdk: oraclejdk8

branches:
  only:
  - master
  
script:
- ./gradlew check --stacktrace --info

install:
  echo yes | sdkmanager "platform-tools",
  echo yes | sdkmanager "platforms;android-26"
