language: android

sudo: true

android:
  components:
  - platform-tools
  - build-tools-28.0.3
  - android-26

jdk: oraclejdk8

branches:
  only:
  - master
  
script:
- ./gradlew check --stacktrace --info
