language: android

sudo: true

android:
  components:
  - tools # to update the repository XML files
  - tools # to update the SDK tools themselves

  - platform-tools
  - build-tools-28.0.3
  - android-26

jdk: oraclejdk8

branches:
  only:
  - master
  
script:
- ./gradlew check --stacktrace --info

install:
  echo yes | sdkmanager "platform-tools",
  echo yes | sdkmanager "platforms;android-26"
